name: Continuous Integration

on:
  workflow_dispatch:
  pull_request: {}
  push: { branches: [main] }

jobs:
  lint:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with: { python-version: "3.12" }

    - name: Install linters
      run: >-
        sudo apt-get update -q
        && sudo apt-get install clang-format cmake-format -y -q

    - uses: pre-commit/action@v3.0.1
      with:
        extra_args: --all-files --show-diff-on-failure
      env:
        SKIP: clang-tidy

  test:
    needs: [lint]
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install static analyzers
      run: >-
        sudo apt-get update -q
        && sudo apt-get install clang-tidy -y -q

    - name: Configure
      run: cmake --preset host-release

    - name: Build
      run: cmake --build --preset host-release

    - name: Test
      run: ctest --preset host-release -j 2

    - name: Configure for clang-tidy
      run: cmake --preset host-debug

    - name: Analyze
      uses: pre-commit/action@v3.0.1
      with:
        extra_args: clang-tidy --all-files --show-diff-on-failure

  docs:
    needs: [lint]
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install Doxygen
      run: sudo apt-get update -q
        && sudo apt-get install doxygen graphviz -q -y

    - name: Build docs
      run: mkdir -p build/ && doxygen docs/Doxyfile

    - uses: actions/upload-pages-artifact@v3
      with:
        path: build/docs/html

  deploy-docs:
    needs: [test, docs]
    runs-on: ubuntu-24.04

    if: github.ref == 'refs/heads/main'
      && github.repository_owner == 'AndreaRicchi'

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    concurrency:
      group: github-pages
      cancel-in-progress: false

    steps:
    - id: deployment
      uses: actions/deploy-pages@v4
